# Generated by Django 3.0.3 on 2020-05-27 10:17

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20200505_0126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.FileField(
                storage=gdstorage.storage.GoogleDriveStorage(), upload_to='ArticleAssets/'),
        ),
    ]
