# Generated by Django 3.0.3 on 2020-05-04 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelFirst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('address', models.CharField(max_length=50, verbose_name='Address')),
            ],
            options={
                'verbose_name': 'ModelFirst',
                'verbose_name_plural': 'ModelFirsts',
            },
        ),
        migrations.CreateModel(
            name='ModelSecond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession', models.CharField(max_length=50, verbose_name='Address')),
                ('person', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='checkapp.ModelFirst', verbose_name='Person')),
            ],
            options={
                'verbose_name': 'ModelSecond',
                'verbose_name_plural': 'ModelSeconds',
            },
        ),
    ]
