# Generated by Django 3.0.3 on 2020-05-04 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelsecond',
            name='profession',
            field=models.CharField(max_length=50, verbose_name='Profession'),
        ),
    ]
