# Generated by Django 3.0.3 on 2020-06-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='subscriber',
            name='subscriber',
            field=models.EmailField(max_length=254, unique=True, verbose_name='subscriber_email'),
        ),
    ]
