# Generated by Django 3.0.3 on 2020-06-30 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200630_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='read',
            field=models.BooleanField(default=False, verbose_name='Read or Not Read'),
        ),
        migrations.AddField(
            model_name='contact',
            name='sent_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Sent On'),
        ),
        migrations.AddField(
            model_name='subscriber',
            name='subscribed_on',
            field=models.DateTimeField(auto_now=True, verbose_name='subscribed_on'),
        ),
    ]
