# Generated by Django 3.0.3 on 2020-05-08 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200506_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='_usermodel_followed_by_+', to='accounts.UserModel', verbose_name='Followed by'),
        ),
    ]
