# Generated by Django 3.0.3 on 2020-05-13 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usermodel_followed_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='Client IP')),
            ],
            options={
                'verbose_name': 'IPAddress',
                'verbose_name_plural': 'IPAddresses',
            },
        ),
    ]
