# Generated by Django 3.0.3 on 2020-06-10 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20200527_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='dark_mode',
            field=models.BooleanField(default=False, verbose_name='Dark or Light Mode'),
        ),
    ]
