# Generated by Django 3.0.3 on 2020-05-04 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0026_auto_20200504_0826'),
        ('photos', '0002_auto_20161122_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Article', verbose_name='Article Gallary'),
        ),
    ]
