# Generated by Django 3.0.3 on 2020-05-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20200504_1725'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='article',
        ),
    ]
