# Generated by Django 3.0.3 on 2020-05-04 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ('-uploaded_at',), 'verbose_name': 'Photo', 'verbose_name_plural': 'Photos'},
        ),
    ]
