# Generated by Django 3.0.2 on 2020-01-31 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(max_length=200)),
                ('content', models.TextField()),
                ('ratings', models.CharField(choices=[('1', 'one star'), ('2', 'two star'), ('3', 'three star'), ('4', 'four star'), ('5', 'five star')], default='1', max_length=2, verbose_name='ratinngs')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Writer')),
            ],
        ),
    ]
