# Generated by Django 3.0.2 on 2020-04-27 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0006_auto_20200420_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='ratings',
            field=models.CharField(choices=[('1', 'one star'), ('2', 'two star'), ('3', 'three star'), ('4', 'four star'), ('5', 'five star')], default='1', max_length=2, verbose_name='ratings'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='testapp.Article')),
            ],
        ),
    ]
