# Generated by Django 3.0.2 on 2020-04-27 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_auto_20200427_2009'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
