# Generated by Django 3.0.2 on 2020-04-28 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0009_delete_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='gallery_content',
            field=models.FileField(blank=True, null=True, upload_to='article_stuffs', verbose_name='Gallery'),
        ),
    ]
