# Generated by Django 3.0.2 on 2020-04-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0010_article_gallery_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery_content', models.FileField(blank=True, null=True, upload_to='article_stuffs', verbose_name='Gallery')),
            ],
            options={
                'verbose_name': 'Gallery',
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='gallery_content',
        ),
        migrations.AddField(
            model_name='article',
            name='article_content',
            field=models.ManyToManyField(related_name='images', to='testapp.Gallery', verbose_name='Gallaries'),
        ),
    ]
