# Generated by Django 3.0.2 on 2020-04-28 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0012_auto_20200428_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
