# Generated by Django 2.2.9 on 2020-04-28 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0013_remove_article_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_content',
        ),
        migrations.AddField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='testapp.Article', verbose_name='article_content'),
        ),
    ]
