# Generated by Django 3.0.2 on 2020-04-28 07:33

from django.db import migrations, models
import django.db.models.deletion
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0014_auto_20200428_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='testapp.Article', verbose_name='article_content'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='gallery_content',
            field=models.FileField(blank=True, null=True, upload_to=testapp.models.set_Image_name, verbose_name='Gallery'),
        ),
    ]
