# Generated by Django 3.0.2 on 2020-05-01 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testapp', '0018_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='has_liked',
            field=models.ManyToManyField(null=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Likers'),
        ),
    ]
