# Generated by Django 3.0.2 on 2020-05-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0020_auto_20200502_0106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='like_status',
        ),
    ]
