# Generated by Django 3.0.2 on 2020-05-03 07:58

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0021_remove_article_like_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'managed': True, 'ordering': ('-pub_date',), 'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AddField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=testapp.models.set_Image_name, verbose_name='Thumbnail'),
        ),
    ]
