# Generated by Django 3.0.3 on 2020-05-03 14:13

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0022_auto_20200503_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=testapp.models.set_thumbnail_name, verbose_name='Thumbnail'),
        ),
    ]
