# Generated by Django 3.0.3 on 2020-05-04 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0024_auto_20200504_0756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_content',
            field=models.FileField(blank=True, null=True, upload_to='uploaded_using_plugin/', verbose_name='Gallery'),
        ),
    ]
