# Generated by Django 3.0.3 on 2020-05-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0025_auto_20200504_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='gallery_content',
            field=models.FileField(upload_to='uploaded_using_plugin/', verbose_name='Gallery'),
        ),
    ]
