# Generated by Django 3.0.3 on 2020-05-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_remove_photo_article'),
        ('testapp', '0026_auto_20200504_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='assets',
            field=models.ManyToManyField(to='photos.Photo'),
        ),
    ]
