# Generated by Django 3.0.3 on 2020-05-08 01:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20200506_1504'),
        ('testapp', '0031_article_followed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='followed_by',
            field=models.ManyToManyField(blank=True, related_name='followers', to='accounts.UserModel', verbose_name='Followed by'),
        ),
        migrations.AlterField(
            model_name='article',
            name='has_liked',
            field=models.ManyToManyField(blank=True, related_name='likes', to=settings.AUTH_USER_MODEL, verbose_name='Likers'),
        ),
    ]
