# Generated by Django 3.0.3 on 2020-05-08 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0032_auto_20200508_0724'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='followed_by',
        ),
    ]
