# Generated by Django 3.0.3 on 2020-05-13 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0033_remove_article_followed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Viewed'),
            preserve_default=False,
        ),
    ]
