# Generated by Django 3.0.3 on 2020-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0034_article_views_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Viewed'),
        ),
    ]
