# Generated by Django 3.0.3 on 2020-05-13 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ipaddress'),
        ('testapp', '0036_article_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='client_ip',
            field=models.ManyToManyField(blank=True, related_name='clients_ip', to='accounts.IPAddress', verbose_name='Client IP'),
        ),
    ]
