# Generated by Django 3.0.3 on 2020-05-17 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_usermodel_favourites'),
        ('testapp', '0038_auto_20200516_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='accounts.UserModel'),
        ),
    ]
