# Generated by Django 3.0.3 on 2020-05-17 09:38

from django.db import migrations, models
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0040_auto_20200517_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=testapp.models.set_category_thumbnail_name, verbose_name='CategoryImage'),
        ),
    ]
