# Generated by Django 3.0.3 on 2020-05-17 15:52

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0041_category_cat_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=tinymce.models.HTMLField(verbose_name='Article description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='About Category'),
        ),
    ]
