# Generated by Django 3.0.3 on 2020-05-18 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0043_auto_20200517_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='last_updated',
            field=models.DateTimeField(verbose_name='Last Updated'),
        ),
    ]
