# Generated by Django 3.0.3 on 2020-05-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0044_auto_20200518_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='blog_type', to='testapp.Category', verbose_name='Blog Category'),
        ),
    ]
