# Generated by Django 3.0.3 on 2020-05-27 16:20

from django.db import migrations, models
import gdstorage.storage
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0047_auto_20200523_1853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=testapp.models.set_thumbnail_name, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_thumbnail',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=testapp.models.set_category_thumbnail_name, verbose_name='CategoryImage'),
        ),
    ]
