# Generated by Django 3.0.3 on 2020-05-27 18:09

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0048_auto_20200527_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='thumbnail',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='article_thumbnail', verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_thumbnail',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to='category_thumbnail', verbose_name='CategoryImage'),
        ),
    ]
