# Generated by Django 3.0.3 on 2020-05-27 19:31

from django.db import migrations, models
import gdstorage.storage
import testapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0050_auto_20200528_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_thumbnail',
            field=models.FileField(blank=True, null=True, storage=gdstorage.storage.GoogleDriveStorage(), upload_to=testapp.models.set_category_thumbnail_name, verbose_name='CategoryImage'),
        ),
    ]
