# Generated by Django 3.0.2 on 2020-04-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
    ]
