# Generated by Django 3.0.2 on 2020-04-28 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0015_auto_20200428_1318'),
        ('likecomment', '0003_like_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='testapp.Article', verbose_name='article'),
        ),
    ]
