# Generated by Django 3.0.2 on 2020-04-30 09:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0005_auto_20200428_2234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_txt',
            field=tinymce.models.HTMLField(verbose_name='Comments'),
        ),
    ]
