# Generated by Django 3.0.2 on 2020-05-01 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0007_auto_20200501_1614'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
