# Generated by Django 3.0.2 on 2020-05-03 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0008_delete_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_txt',
            field=models.TextField(verbose_name='Comments'),
        ),
    ]
