# Generated by Django 3.0.3 on 2020-05-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0009_auto_20200503_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_txt',
            field=models.TextField(verbose_name=''),
        ),
    ]
