# Generated by Django 3.0.3 on 2020-05-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0010_auto_20200504_1013'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='clapped',
            field=models.IntegerField(default=0, verbose_name='Clapped Counts'),
            preserve_default=False,
        ),
    ]
