# Generated by Django 3.0.3 on 2020-05-06 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likecomment', '0012_auto_20200506_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='clapped',
            field=models.IntegerField(default=0, verbose_name='Clapped Counts'),
        ),
    ]
