# Generated by Django 3.0.3 on 2020-05-13 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usermodel_followed_by'),
        ('likecomment', '0013_auto_20200506_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.UserModel', verbose_name='UserName'),
        ),
    ]
